Issue/replace pay pal pro
HotcakesCommerce/hotcakes-commerce-core pull request #442
Opened 2023-01-12 13:37 UTC by VAlmea

Here are present all the necessary changes to update the implementation of PayPal Pro. Also removed unnecessary classes and references. There is also a little modification to the class startPayPalExpressCheckout.cs that I realized was needed when I removed the reference to the old paypal_base.dll. 

close#49

2023-01-12 18:04 UTC, WillStrohl requested changes
This mostly looks good, but there is a single question so far about the code.  Also, I have another question that I'll send to you internally.

2023-01-12 18:04 UTC, WillStrohl commented on Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs
> +                        Name = "John Doe",
Why is this using "John Doe"?

2023-01-12 18:05 UTC, WillStrohl commented
@VAlmea  Oh, your close comment is attempting to close the previous PR and not the original Issue.  :)

2023-01-14 09:58 UTC, VAlmea commented on Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs
> +                        Name = "John Doe",
Solved

2023-01-17 19:11 UTC, WillStrohl approved these changes
Looks good, but needs to be tested still.

2023-01-17 19:11 UTC, merged